spring:
  common-web:
    messages:
      basename: classpath:i18n/messages
      encoding: UTF-8
    api-log:
      type: all
    format:
      pattern:
        date-time: dd/MM/yyyy HH:mm:ss
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Da0ben2014
    url: jdbc:mysql://192.168.42.66:3306/dto_transform_test?characterEncoding=UTF-8
    platform: mysql